version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyWeirdPass!
    volumes:
      - /home/oxigenocc/data-db/:/var/lib/postgresql/data
  web:
    restart: always
    build: .
    command: bash -c "./entrypoint.sh"
    ports:
      - "8000:8000"
    depends_on:
      - db
