version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyWeirdPass!
  web:
    restart: always
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 mysite.wsgi:application"
    ports:
      - "8080:8080"
    depends_on:
      - db

